---
- hosts: all
  become: true
  tasks:

  - name: update distibution
    apt:
      update_cache: yes
  - name: install apache
    apt:
      name:
        - apache2
      update_cache: yes

  - name: copy index html
    copy: 
      src: conf/index.html
      dest: /var/www/html/
